### ISSUE TITLE
exception starting pretix after installing the plugin

### ISSUE THREAD

**Issue by ligi** [vic-en/pretix-eth-payment-plugin#11]
I just installed the plugin - before pretix was working fine - but afterwards I am getting this:

```
Watching for file changes with StatReloader
INFO 2019-05-17 18:42:51,423 django.utils.autoreload autoreload Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/ligi/git/pretix/src/env/lib/python3.5/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration pretix_eth.0001_initial dependencies reference nonexistent parent node ('pretixbase', '0109_auto_20190215_1700')

```

**Comment by raphaelm** [comment]
The parent migration ``0109_auto_20190215_1700`` doesn't exist in pretix, so apparently @vic-en had a modified pretix migration history when he created the plugin.

**Comment by ligi** [comment]
@raphaelm thanks for the input!

**Comment by ligi** [comment]
as this repository is unmaintained - moving to: https://github.com/esPass/pretix-eth-payment-plugin/issues/6
